# Generated by Django 5.2.8 on 2025-11-30 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Formato SKU inválido. Use AAA-0000', regex='^[A-Z]{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(choices=[('Basico', 'Básico'), ('Estandar', 'Estándar'), ('Premium', 'Premium')], default='Basico', max_length=20),
        ),
    ]
